language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script:
- jdk_switcher use oraclejdk7
- gradle clean
- gradle build
- gradle test
- jdk_switcher use oraclejdk8
- gradle clean
- gradle build
- gradle test
