addons:
  sonarqube: true
env:
  global:
    - secure: "nPh4tS+SEWHXmm4keHBLQSVMdwMyUJRFNDFhYt+DezK4ruU8D0ZFhssY3I7anhX/FZ4pG64uVjXWcaIIqZMzJvs4000Z3Ym+7sC/3HSV27qdjQCvJPp6tjfkWtSPomqaW8MPmrG69KZNlANYrbAkMcPTR7zxCYwwnMfQurRmFi80d/2O5xCw5NxXBeJ/6nPmiUtpN8njdI4yhSjrBtYuGtwjm0zh1ZAo6l/1928+qXKooXXDHM1d1qpMgIB3sQW6ggSrpJy2W0tfEaUHbMB+MIoOuu3QdVvpicw61Vb23jGNrnsSvBDFi0ydYlmGaKzz9Fss1jMGQEon1ik/rA83VLZ7HusfF7JjDv+2ZArIGyL6BoDRUkadpPP3KIeWgVRA634GZAkqxz4zarEHjTMTK7mgolw6H9vnTabfcCabhmHVmaf+ZCHhXQZHku7ScxRMl6oPLyZSCluuvq9ISq7B/iHSuIdXgzUZreflYip6uYiTqmLtDvtIN0L7yj1elZtmE1suSDCkSOLIw92h0u27mW2JFNRKzjdaafSYjyLB/4IAoGSbLPKeWY0Dqg1eQSGQWLkRKxGhx5AtdtOUvX0VesyGor8g4UvFCmPvriONhPBShWBHP18CLwigFfKSDlIcUH2idhs/O1Uxsyti20tXv1hjhWntinv+9ekHj5/S6Dw="
language: java
script:
- jdk_switcher use oraclejdk7
- gradle clean
- gradle build
- gradle test
- jdk_switcher use oraclejdk8
- gradle clean
- gradle build
- gradle test
- sonar-scanner -Dsonar.login=$SONAR_HCL 
